### ISSUE TITLE
What's the proper way to restart with bigger MaxM

### ISSUE THREAD

**Issue by jeanwsr** [pyscf/dmrgscf#4]
Dear developers,

When I try to restart a previous DMRG calculation with bigger MaxM, I found it doesn't work like I expect.
First I do a DMRG with block, with MaxM=800 (CASCI E = -199.289259), and then restart it with MaxM=1500(CASCI E = -199.289292). But if I do MaxM=1500 directly, I get CASCI E = -199.293747, which is lower than the restart job.

I guess the reason is that the related code in `dmrgci.writeDMRGConfFile()` does not make a schedule for restart job, so the solution is trapped.
```
    if (not Restart):
        ...
    else :
        f.write('schedule\n')
        f.write('0 %6i  %8.4e  %8.4e \n' %(DMRGCI.maxM, DMRGCI.tol/10, 0e-6))
```
And it does not allow me to define a schedule for restart job. 

Do you have any suggestion or idea for a proper restart job?

**Comment by hczhai** [comment]
Hi,

(1) The ``DMRGCI.restart`` attribute is mainly used for converging a DMRGSCF where the 1-site DMRG algorithm is used and ``maxM`` is not expected to be changed. It gives higher energy than a non-restarting DMRG with ``maxM = 1500`` because the restating schedule is simpler and 1-site DMRG is not as good as 2-site DMRG for getting lower energies.

(2) If you want to restart DMRG using a larger ``maxM`` to get a more accurate energy, you may use the ``DMRGCI.extraline`` attribute for adding the ``fullrestart`` keyword (and avoid setting ``DMRGCI.restart = True``). The following is an example script:

    # 1. normal casci-dmrg
    
    mc = mcscf.CASCI(mf, nactorb, nactelec)
    mc.fcisolver = dmrgscf.DMRGCI(mol, maxM=500, tol=1E-10)
    mc.fcisolver.threads = int(os.environ.get("OMP_NUM_THREADS", 4))
    mc.fcisolver.memory = int(mol.max_memory / 1000) # mem in GB
    mc.kernel(mf.coeff)
    
    # 2. restarting with a new schedule
    
    mc.fcisolver.clearSchedule()
    mc.fcisolver.startM = 500
    mc.fcisolver.maxM = 750
    mc.fcisolver.generate_schedule()
    mc.fcisolver.extraline = ["fullrestart"]
    mc.kernel(mf.coeff)

**Comment by jeanwsr** [comment]
Thank you very much!
